/**
 * packager.js
 *
 * Assembles the download ZIP from:
 *   - Student source files (from API)
 *   - vpl_evaluate.cases (fetched or reconstructed)
 *   - run_tests.py (bundled resource)
 *   - README.md (generated)
 *
 * Requires JSZip to be available as window.JSZip.
 */

const VPLocalPackager = (function () {
  "use strict";

  function generateReadme({ assignmentName, caseCount, fetched, reconstructed, manual, lang }) {
    const lines = [
      `# VPLocal — ${assignmentName}`,
      "",
      "## Quick Start",
      "",
      "```bash",
      "python3 run_tests.py",
      "```",
      "",
      "Options:",
      "  `--case N`       Run only case number N",
      "  `--no-color`     Disable ANSI color",
      "  `--timeout N`    Per-case timeout in seconds (default: 10)",
      "",
      "## Test Case Coverage",
      "",
    ];

    if (fetched > 0) {
      lines.push(`- **${fetched}** case(s) fetched directly from the server ✓`);
    }
    if (reconstructed > 0) {
      lines.push(`- **${reconstructed}** case(s) reconstructed from evaluation feedback`);
      lines.push("  > Only failed cases are captured. Cases you passed on the recorded run");
      lines.push("  > are not included here — your code already handles those.");
    }
    if (manual > 0) {
      lines.push(`- **${manual}** case(s) entered manually`);
    }

    lines.push("");
    lines.push("## Language");
    lines.push("");
    lines.push(`Detected: **${lang || "auto-detect"}**`);
    lines.push("");
    lines.push("Requires:");
    if (!lang || lang === "c") lines.push("- `gcc` (C compiler)");
    if (lang === "cpp") lines.push("- `g++` (C++ compiler)");
    if (lang === "python") lines.push("- `python3`");
    lines.push("");
    lines.push("---");
    lines.push("*Generated by [VPLocal](https://github.com/vazleo/vplocal)*");
    lines.push("");

    return lines.join("\n");
  }

  function slugify(str) {
    return str
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "_")
      .replace(/^_+|_+$/g, "")
      .slice(0, 40) || "assignment";
  }

  function detectLangFromFiles(sourceFiles) {
    for (const f of sourceFiles) {
      if (f.name.endsWith(".c")) return "c";
      if (f.name.endsWith(".cpp") || f.name.endsWith(".cxx")) return "cpp";
      if (f.name.endsWith(".py")) return "python";
      if (f.name.endsWith(".java")) return "java";
    }
    return null;
  }

  /**
   * Build and trigger download of the VPLocal ZIP.
   *
   * @param {object} opts
   *   assignmentName  string  - name of the VPL activity
   *   casesText       string  - contents of vpl_evaluate.cases
   *   sourceFiles     Array<{name, data}>  - student source files
   *   runnerSource    string  - contents of run_tests.py
   *   coverage        { fetched, reconstructed, manual }
   */
  async function buildAndDownload(opts) {
    if (typeof JSZip === "undefined") {
      throw new Error("JSZip is not loaded. Check @require in userscript header.");
    }

    const {
      assignmentName = "assignment",
      casesText = "",
      sourceFiles = [],
      runnerSource = "",
      coverage = { fetched: 0, reconstructed: 0, manual: 0 },
    } = opts;

    const lang = detectLangFromFiles(sourceFiles);
    const slug = slugify(assignmentName);
    const folderName = `vplocal_${slug}`;

    const zip = new JSZip();
    const folder = zip.folder(folderName);

    // Student source files
    for (const f of sourceFiles) {
      folder.file(f.name, f.data);
    }

    // Test cases
    folder.file("vpl_evaluate.cases", casesText);

    // Runner script
    if (runnerSource) {
      folder.file("run_tests.py", runnerSource);
    }

    // README
    const readme = generateReadme({
      assignmentName,
      caseCount: (casesText.match(/^case\s*=/gim) || []).length,
      ...coverage,
      lang,
    });
    folder.file("README.md", readme);

    // Generate and trigger download
    const blob = await zip.generateAsync({ type: "blob" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${folderName}.zip`;
    document.body.appendChild(a);
    a.click();
    setTimeout(() => {
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
    }, 1000);
  }

  return { buildAndDownload, detectLangFromFiles };
})();
